version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker

    frontend:
        container_name: frontend
        image: frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3001:3000
